# Config file for air (hot-reloading)
root = "."
tmp_dir = "tmp"
[build]
  cmd = "go build -o tmp/main main.go"
  bin = "tmp/main"
  delay = "100ms"
  exclude_dir = ["tmp", "vendor"]
  exclude_file = ["README.md"]
  full_bin = false
  log = "air_errors.log"
  stop_on_error = true

